export const Content=[
    {id:1,name:'suleman',email:'suleman@gmail.com'},
    {id:2,name:'Yaseen',email:'yaseen@gmail.com'},
    {id:3,name:'Qalander',email:'qalander@gmail.com'},
    {id:4,name:'Raheel',email:'raheel@gmail.com'},
    {id:5,name:'Imran',email:'imran@gmail.com'},
    {id:6,name:'shadab',email:'shadab@gmail.com'},
    {id:7,name:'malik',email:'malik@gmail.com'},
    {id:8,name:'yasir',email:'yasir@gmail.com'},
    {id:9,name:'kamran',email:'kamran@gmail.com'},
    {id:10,name:'shahid',email:'shahid@gmail.com'},
    {id:11,name:'jameel',email:'jameel@gmail.com'},
    {id:12,name:'umer',email:'umer@gmail.com'},
    {id:13,name:'nadeem',email:'nadeem@gmail.com'},
    {id:14,name:'ali',email:'ali@gmail.com'},
]